version: '3.7'

services:
  gateway:
    image: app_flight:v2
    container_name: app_flight
    build:
      context: ./api-gateway
    env_file: .env
    ports:
      - 80:3000
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_flights

  microservice-flights:
    image: microservice_flight:v2
    container_name: microservice-flights
    build:
      context: ./microserviceFlight
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_flights

  microservice-passengers:
    image: microservice_passengers:v2
    container_name: microservice-passengers
    build:
      context: ./microservicePassenger
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_flights

  microservice-users:
    image: microservice_users:v2
    container_name: microservice-users
    build:
      context: ./microserviceUsers
    env_file: .env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    networks:
      - ms_flights

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq
    expose:
      - 5672
      - 15672
    restart: always
    networks:
      - ms_flights

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - 27017
    networks:
      - ms_flights

volumes:
  mongodb:

networks:
  ms_flights: