export enum RabbitMQ {
  UserQueue = 'users',
  PassengerQueue = 'passengers',
  FlightQueue = 'flights',
}

export enum UserMSG {
  CREATE = 'CREATE_USER',
  GET_ALL = 'GET_USERS',
  GET_ONE = 'GET_USER',
  UPDATE = 'UPDATE_USER',
  DELETE = 'DELETE_USER',
  VALID_USER = 'VALID_USER',
}

export enum PassengerMSG {
  CREATE = 'CREATE_PASSENGER',
  GET_ALL = 'GET_PASSENGERS',
  GET_ONE = 'GET_PASSENGER',
  UPDATE = 'UPDATE_PASSENGER',
  DELETE = 'DELETE_PASSENGER',
  VALID_PASSENGER = 'VALID_PASSENGER',
}

export enum FlightMSG {
  CREATE = 'CREATE_FLIGHT',
  GET_ALL = 'GET_FLIGHTS',
  GET_ONE = 'GET_FLIGHT',
  UPDATE = 'UPDATE_FLIGHT',
  DELETE = 'DELETE_FLIGHT',
  VALID_FLIGHT = 'VALID_FLIGHT',
  ADD_PASSENGER = 'ADD_PASSENGER',
}
